name: catalog service Server ci cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "catalog-service/**"

jobs:
  build-and-deploy:
    name: build project & push docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalog-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          
      - name: Build with maven
        run: mvn clean package -DskipTests -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: catalog-service-build
          path: ./catalog-service/target/
          retention-days: 1

      - name: run tests
        run: mvn test -s ${{ github.workspace }}/settings.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: catalog-service-build
          path: ./catalog-service/target/
          
      - name: Push Docker image
        run: mvn jib:build -DskipTests -s ${{ github.workspace }}/settings.xml
      
