name: common util ci pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "common-util/**"

jobs:
  maven-build-test-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common-util
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github

      - name: Build with maven
        run: mvn -B package --file pom.xml
      
      - name: Publish to GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}
        
