name: config server ci cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "atozmart-configserver/**"

jobs:
  maven-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./configserver
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          
      - name: Build with maven
        run: mvn clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: run tests
        run: mvn test

      - name: Publish to GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          
      - name: Push Docker image
        run: mvn compile jib:build -DskipTests

  deploy-to-ec2:
    needs: maven-build-and-test
    runs-on: configserver-ec2-runner
    defaults:
      run:
        working-directory: /home/ubuntu/atozmart-configserver
    steps:
      - name: find running instance
        run: |
          PID=$(sudo pgrep -f "atozmart-configserver-.*.jar")
          echo "CONFIG_PID=$PID" >> $GITHUB_ENV

      - name: stop running instance
        run: |
          if [ -z "$CONFIG_PID" ]; then
            echo "No running instance found. Skipping stop command."
          else
            echo "Found process $CONFIG_PID. Stopping now..."
            sudo kill -15 $CONFIG_PID
          fi
          
      - name: remove old jar file
        run: |
          sudo rm -rf *
      
      - name: download artifact
        uses: actions/download-artifact@v7.0.0
        with:
          artifact-ids: atozmart-configserver
          github-token: ${{ secrets.PAT_GITHUB }}

      - name: run jar file
        run: |
          JAR_FILE=$(ls *.jar)
          echo "Running $JAR_FILE"
          nohup java -jar $JAR_FILE \ 
          --spring.profiles.active=prod \
          --encrypt.keyStore.password=${{ secrets.KEYSTORE_PASSWORD }} \
          --logging.file.name=./atozmart-configserver.log \
          &
