name: config server ci cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "atozmart-configserver/**"

jobs:
  maven-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./configserver
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          
      - name: Build with maven
        run: mvn clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: run tests
        run: mvn test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: atozmart-configserver
          path: configserver/target
          retention-days: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          
      - name: Push Docker image
        run: mvn compile jib:build -DskipTests

  deploy-to-ec2:
    needs: maven-build-and-test
    runs-on: configserver-runner-ec2
    defaults:
      run:
        working-directory: /home/ubuntu/atozmart-configserver
    steps:
      - name: stop running instance
        run: |
          sudo systemctl stop atozmart-configserver.service

      - name: remove old artifacts
        run: |
          sudo rm -rf * || true
      
      - name: download new artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: atozmart-configserver
          path: /home/ubuntu/atozmart-configserver/
          github-token: ${{ secrets.PAT_GITHUB }}

      - name: run jar file
        run: |
          JAR_FILE=$(ls atozmart-configserver-*.jar | head -n 1)
          echo "creating local .env file"
          echo "JAR_FILE=$JAR_FILE" >> atozmart-configserver.env
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> atozmart-configserver.env
          # Set restrictive permissions so only the owner can read it
          chmod 600 atozmart-configserver.env
          sudo systemctl daemon-reload
          echo "Running $JAR_FILE"
          sudo systemctl restart atozmart-configserver.service
