name: eureka server ci cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "eurekaserver/**"

jobs:
  maven-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./eurekaserver
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          
      - name: Build with maven
        run: mvn clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: run tests
        run: mvn test

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          
      - name: Push Docker image
        run: mvn compile jib:build -DskipTests
