name: exception handler ci cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "common-util/exception-handler/**"

jobs:
  maven-build-test-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common-util/exception-handler
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with maven
        run: mvn -B package --file pom.xml
      
      - name: Publish to GitHub Packages
        run: mvn deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
        
