name: exception handler ci cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "common-util/exception-handler/**"

jobs:
  maven-build-test-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common-util/exception-handler
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with maven
        run: mvn clean package -DskipTests

      - name: run tests
        run: mvn test
      
      - name: Publish to GitHub Packages
        run: mvn deploy -DskipTests --settings .github/maven-settings.xml
